security:
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    ROLE_ADMIN: [ROLE_USER]

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      form_login:
        login_path: app_auth          # GET /auth (affichage)
        check_path: app_auth          # POST /auth (soumission)
        enable_csrf: true
        csrf_token_id: authenticate   # correspond à {{ csrf_token('authenticate') }}
        username_parameter: email     # <input name="email">
        password_parameter: password  # <input name="password">

      logout:
        path: app_logout
        target: app_home

  access_control:
    - { path: ^/auth$, roles: PUBLIC_ACCESS }
    - { path: ^/mot-de-passe/(oublie|reinitialiser), roles: PUBLIC_ACCESS }
    - { path: ^/(_(profiler|wdt)|css|images|js)/, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/mon-espace, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10


parameters:
  mailer_from: '%env(MAILER_FROM)%'
