security:
    # Encodage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Chargement de l'utilisateur
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_USER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true

            logout:
                path: app_logout
                # target: app_home

            # switch_user: true (facultatif si tu veux l’usurpation d’identité pour tests)

    access_control:
        # L’espace admin est accessible à ROLE_ADMIN et plus
        - { path: ^/admin, roles: ROLE_ADMIN }
        # L’espace "Mon espace" pour les utilisateurs authentifiés
        - { path: ^/mon-espace, roles: ROLE_USER }
        # L’espace Intranet accessible aux employés (ROLE_ADMIN)
        - { path: ^/intranet, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
