app = "cinephoria-web"
primary_region = "cdg" # Paris

[build]
  dockerfile = "Dockerfile.fly"

# Service HTTP (Machines v2)
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  # Health check HTTP
  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/healthz"

# Commande exécutée à chaque déploiement (migrations + cache)
[deploy]
  # Forme minimale et robuste (évite le parsing foireux des options)
  release_command = "php bin/console doctrine:migrations:migrate -n && php bin/console cache:clear -n --env=prod && php bin/console cache:warmup -n --env=prod"

# Montage du volume persistant (uploads)
[[mounts]]
  source = "uploads"
  destination = "/app/public/uploads"

# Variables d'environnement runtime
[env]
  APP_ENV = "prod"
  TZ = "Europe/Paris"
  LANG = "fr_FR.UTF-8"
  LANGUAGE = "fr_FR:fr"
  LC_ALL = "fr_FR.UTF-8"
