# config/services.yaml
parameters:
  # Adresse affichée (site / emails)
  app.support_email_display: 'contact@cinephoria.fr'
  # Destinataire réel (pour la livraison des mails)
  app.support_email_delivery: 'kev7@live.fr'

  # Valeurs par défaut si MONGODB_DB / MONGODB_COLLECTION ne sont pas fournis
  mongodb.db.default: 'cinephoria'
  mongodb.collection.default: 'reservations'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Client MongoDB basé sur l'URI d'environnement
  MongoDB\Client:
    arguments:
      $uri: '%env(resolve:MONGODB_URI)%'

  # Ton logger Mongo : injection du client + noms DB/collection avec fallback
  App\Service\MongoReservationsLogger:
    arguments:
      $client: '@MongoDB\Client'
      $dbName: '%env(default:mongodb.db.default:MONGODB_DB)%'
      $collectionName: '%env(default:mongodb.collection.default:MONGODB_COLLECTION)%'

  # Make classes in src/ available as services
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Injection des paramètres e-mail dans le contrôleur Contact
  App\Controller\ContactUserController:
    bind:
      string $supportDisplayEmail: '%app.support_email_display%'
      string $supportDeliveryEmail: '%app.support_email_delivery%'
