# config/services.yaml
# Entry point to configure your own services and parameters.

parameters:
  # Adresse affichée (site / emails)
  app.support_email_display: 'contact@cinephoria.fr'
  # Destinataire réel (pour la livraison des mails)
  app.support_email_delivery: 'kev7@live.fr'

services:
  # Default configuration for services in this file
  _defaults:
    autowire: true
    autoconfigure: true

  MongoDB\Client:
    arguments:
      $uri: '%env(resolve:MONGODB_URI)%'

  # Make classes in src/ available as services
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Injecte les paramètres e-mail dans ContactUserController
  App\Controller\ContactUserController:
    bind:
      string $supportDisplayEmail: '%app.support_email_display%'
      string $supportDeliveryEmail: '%app.support_email_delivery%'
