name: CI / CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: PHPUnit (Symfony)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        ports: [ "5432:5432" ]
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: sandbox_cinephoria_test
        options: >-
          --health-cmd="pg_isready -U app -d sandbox_cinephoria_test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

      mongo:
        image: mongo:6
        ports: [ "27017:27017" ]
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok'"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      APP_ENV: test
      APP_DEBUG: 1
      KERNEL_CLASS: App\Kernel
      TRUSTED_HOSTS: ^.*$
      TRUSTED_PROXIES: 127.0.0.1,REMOTE_ADDR
      DATABASE_URL: postgresql://app:admin@postgres:5432/sandbox_cinephoria_test?serverVersion=16&charset=utf8
      MONGODB_URI: mongodb://localhost:27017
      MONGODB_DB: cinephoria
      MONGODB_COLLECTION: reservations
      MAILER_DSN: smtp://localhost:1025?encryption=null&auth_mode=null
      MAILER_FROM: "Cinephoria <no-reply@cinephoria.test>"
      APP_SECRET: 00000000000000000000000000000000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl, mbstring, pdo_pgsql, pgsql, json, zip
          coverage: none
          tools: composer:v2

      - name: Composer cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/composer/files
            vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare test database (Doctrine schema)
        run: |
          php bin/console doctrine:database:create --env=test || true
          php bin/console doctrine:schema:create --env=test

      - name: Run PHPUnit
        run: |
          rm -rf var/cache/test
          php -d variables_order=EGPCS bin/phpunit

  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: [ test ]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo "🚀 Déploiement en production"
            flyctl deploy --app cinephoria-web --remote-only --build-arg BUILD_ENV=prod
          else
            echo "🚀 Déploiement en staging"
            flyctl deploy --app cinephoria-staging --remote-only --build-arg BUILD_ENV=dev
          fi
